test:
  name: promedios
  description: "Benchmark for the promedios smart contract"
  workers:
    number: 1
  rounds:
    - label: a√±adir_paciente
      description: "Benchmark para actualizar datos de un paciente"
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: benchmarks/scenario/paciente/open_copy.js
        
