test:
  name: promedios
  description: "Benchmark for the promedios smart contract"
  workers:
    number: 1
  rounds:
    - label: a√±adir_paciente
      description: "Benchmark para actualizar datos de un paciente"
      txNumber: 200
      rateControl:  
        type: fixed-rate
        opts:
          tps: 50  
      workload:
        module: benchmarks/scenario/paciente/actualizar_paciente_fijo.js
        
